name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout Archi
        run: curl -sL https://github.com/archimatetool/archi/archive/refs/heads/master.tar.gz | tar xz --strip-components=1

      - name: Build Archi Scripting Plug-in (jArchi)
        uses: ./.github/actions/build-archi-plugin
        with:
          name: com.archimatetool.script
          source: archimatetool/archi-scripting-plugin
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Archi Model Collaboration Plug-in (coArchi2)
        uses: ./.github/actions/build-archi-plugin
        with:
          name: com.archimatetool.modelrepository
          source: archimatetool/archi-modelrepository-plugin2
          token: ${{ secrets.GITHUB_TOKEN }}
