name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout Archi
        run: |
          curl -L https://github.com/archimatetool/archi/archive/refs/heads/master.tar.gz | tar xz --strip-components=1

      - name: Checkout Archi Scripting Plugin
        run: |
          curl -L https://github.com/archimatetool//archi-scripting-plugin/archive/refs/heads/master.tar.gz | tar xz --strip-components=1

      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet
      
      - name: Add Plugin Module
        run: |
          ls
          xmlstarlet ed -L \
            -N x="http://maven.apache.org/POM/4.0.0" \
            -s "/x:project/x:modules" -t elem -n "module" -v "com.archimatetool.script" \
            pom.xml

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build
        working-directory: archi
        run: mvn -B -q clean -DskipTests verify

      - name: List Directories
        run: find . -type d
